# -*- coding: utf-8 -*-
"""ETL Tennis Weekly

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sqd6LXQsRQ86AfAC544plPz-gjwu5VT8
"""

import pandas as pd
import os
from pymongo import MongoClient
from sqlalchemy import create_engine
##from google.colab import userdata

"""# 1. Conexiones

"""

MONGO_URI = os.environ.get('MONGO_URI')
NEON_URI = os.environ.get('NEON_URI')

if not MONGO_URI or not NEON_URI:
    raise Exception("Missing connection URIs")

mongo = MongoClient(MONGO_URI)
db = mongo["test"]

engine = create_engine(NEON_URI)

"""# LEER DATOS"""

#matches = list(db.matches.find())
users = list(db.users.find())
matches = list(db.matches.find())

#print(f"Documents: {len(users)} ")
players_df = pd.DataFrame(users)
matches_df = pd.DataFrame(matches)

players_df = players_df[["_id", "name", "lastname", "email", "phone", "role", "ntrplvl", "gender", "walletBalance", "lastMatchPlayed", "isActive", "createdAt"]]
matches_df = matches_df[["_id", "location", "createdBy", "maxPlayers", "maxBackups", "date", "startTime", "endTime", "price", "status"]]

#players_df.head()
#matches_df.head()

"""# Renombrar"""

players_df = players_df.rename(columns={
    "_id": "player_id",
    "ntrplvl": "ntrp_level",
    "walletBalance": "wallet_balance",
    "lastMatchPlayed": "last_match_played"
})

players_df["player_id"] = players_df["player_id"].astype("str")

players_df=players_df.fillna({
    "wallet_balance": 0
})

######MATCHES DF########

"""# Subir los datos a **NEON**"""

from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("""CREATE TABLE IF NOT EXISTS players(
                      player_id TEXT PRIMARY KEY,
                      name TEXT,
                      lastname TEXT,
                      email TEXT,
                      phone TEXT,
                      role TEXT,
                      ntrp_level FLOAT,
                      gender TEXT,
                      wallet_balance FLOAT,
                      last_match_played TIMESTAMP,
                      isAcive BOOLEAN,
                      created_at TIMESTAMP
                      );
    """))

    ##only one execution as table exists

players_df.to_sql(
    "players_staging",
    engine,
    if_exists="replace",
    index=False
)

"""# UPSERT"""

with engine.connect() as conn:
    conn.execute(text("""
      INSERT INTO  players (
        player_id, name, lastname, email, phone, role, ntrp_level, gender, wallet_balance, last_match_played
      )
      SELECT
        player_id, name, lastname, email, phone, role, ntrp_level, gender, wallet_balance, last_match_played
        FROM players_staging
      ON CONFLICT (player_id)
      DO UPDATE SET
        name = EXCLUDED.name,
        lastname = EXCLUDED.lastname,
        email = EXCLUDED.email,
        phone = EXCLUDED.phone,
        role = EXCLUDED.role,
        ntrp_level = EXCLUDED.ntrp_level,
        gender = EXCLUDED.gender,
        wallet_balance = EXCLUDED.wallet_balance,
        last_match_played = EXCLUDED.last_match_played;
    """))

    print("Players sync OK")
