name: Daily MongoDB Backup

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install MongoDB Database Tools
        run: |
          wget -q https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.12.2.deb
          sudo dpkg -i mongodb-database-tools-ubuntu2204-x86_64-100.12.2.deb

      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Create backup
        run: |
          mkdir -p backup

          FILE="weekly-tennis-$(date +'%Y-%m-%d_%H-%M-%S').archive.gz"

          mongodump \
            --uri="${{ secrets.MONGO_URI }}" \
            --gzip \
            --archive="backup/$FILE"

          echo "BACKUP_FILE=$FILE" >> $GITHUB_ENV

      - name: Configure rclone
        run: |
          echo '${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}' > sa.json

          mkdir -p ~/.config/rclone

          cat > ~/.config/rclone/rclone.conf <<EOF
          [gdrive]
          type = drive
          scope = drive
          service_account_file = sa.json
          root_folder_id = ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          EOF

      - name: Upload backup
        run: |
          rclone copy backup gdrive:

      - name: Verify upload
        run: |
          rclone ls gdrive:

      - name: Delete backups older than 30 days
        run: |
          rclone delete gdrive: --min-age 30d
          rclone rmdirs gdrive: --leave-root
