name: Sync Players Daily

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4   # 👈 actualizado

      - uses: actions/setup-python@v5   # 👈 actualizado
        with:
          python-version: "3.11"

      - run: pip install pymongo pandas sqlalchemy psycopg2-binary

      - run: python sync_players.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          NEON_URI: ${{ secrets.NEON_URI }}
